name: Ordered Map CI - Windows

# Trigger the workflow on push or pull requests for main and develop branches
on:
  push:
    branches:
    - main
    - develop
    paths:
    - '**/*.c'
    - '**/*.cpp'
    - '**/*.h'
    - '**/*.hpp'
    - '**/CMakeLists.txt'
    - '**/Makefile'
    - '**/cmake/**'
    - '.github/workflows/**'
  pull_request:
    branches:
    - main
    - develop
    paths:
    - '**/*.c'
    - '**/*.cpp'
    - '**/*.h'
    - '**/*.hpp'
    - '**/CMakeLists.txt'
    - '**/Makefile'
    - '**/cmake/**'
    - '.github/workflows/**'

jobs:
  build:
    name: Build and Test (Windows)
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          [
            { cc: cl, cxx: cl, label: "MSVC" }, # MSVC Compiler
            { cc: gcc, cxx: g++, label: "MinGW GCC" } # MinGW GCC Compiler
          ]

    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install MinGW (For GCC Support)
      if: matrix.cc == 'gcc'
      run: |
        choco install mingw -y
        echo "C:\ProgramData\chocolatey\bin" >> $env:GITHUB_PATH

    - name: Configure Project
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_C_COMPILER=${{ env.CC }} -DCMAKE_CXX_COMPILER=${{ env.CXX }} -G "NMake Makefiles" ..

    - name: Build Project
      run: |
        cd build
        cmake --build . --config Debug --parallel 2

    - name: Run Tests
      run: |
        cd build
        ctest -C Debug --verbose
